In [1]:
from __future__ import print_function
import numpy as np
import sys
if "../" not in sys.path:
  sys.path.append("../") 
#from lib.envs.gridworld import GridworldEnv
from GridWorldEnv import GridworldEnv

In [2]:
env = GridworldEnv()

In [3]:
def policy_eval(policy, env, discount_factor=1.0, theta=0.00001):
    """
    Evaluate a policy given an environment and a full description of the environment's dynamics.
    
    Args:
        policy: [S, A] shaped matrix representing the policy.
        env: OpenAI env. env.P represents the transition probabilities of the environment.
            env.P[s][a] is a list of transition tuples (prob, next_state, reward, done).
        theta: We stop evaluation once our value function change is less than theta for all states.
        discount_factor: gamma discount factor.
    
    Returns:
        Vector of length env.nS representing the value function.
    """
    next_state = np.empty((env.nS, env.nA), dtype=np.int)
    reward = np.empty((env.nS, env.nA))
    for st in range(env.nS):
        for ac in range(env.nA):
            _, next_state[st, ac], reward[st, ac], _ = env.P[st][ac][0]
    
    # Start with a random (all 0) value function
    V = np.zeros(env.nS)
    while True:
        oldV = np.copy(V) # or oldV = V
        action_value = policy * (reward + discount_factor * V[next_state])
        V = np.sum(action_value, axis = 1)
        if np.max(np.abs(V - oldV)) < theta:
            break
    return V

In [4]:
random_policy = np.ones([env.nS, env.nA]) / env.nA
v = policy_eval(random_policy, env)

In [5]:
print("Value Function:")
print(v)
print()

print("Reshaped Grid Value Function:")
print(v.reshape(env.shape))
print()

Value Function:
[  0.         -13.99989315 -19.99984167 -21.99982282 -13.99989315
 -17.99986052 -19.99984273 -19.99984167 -19.99984167 -19.99984273
 -17.99986052 -13.99989315 -21.99982282 -19.99984167 -13.99989315   0.        ]

Reshaped Grid Value Function:
[[  0.         -13.99989315 -19.99984167 -21.99982282]
 [-13.99989315 -17.99986052 -19.99984273 -19.99984167]
 [-19.99984167 -19.99984273 -17.99986052 -13.99989315]
 [-21.99982282 -19.99984167 -13.99989315   0.        ]]



In [6]:
# Test: Make sure the evaluated policy is what we expected
expected_v = np.array([0, -14, -20, -22, -14, -18, -20, -20, -20, -20, -18, -14, -22, -20, -14, 0])
np.testing.assert_array_almost_equal(v, expected_v, decimal=2)